// SPDX-License-Identifier: GPL-3.0-only
import type { AttachmentPreviewWriter } from '@reimbursd/attachments';
import type { ReceiptDocument } from '@reimbursd/domain';

import { ExpoReceiptPreviewCreator } from '../receipt-preview';

jest.mock('@reimbursd/attachments', () => ({
  defaultAttachmentPreviewLimits: { maximumDimension: 1_600 },
}));

jest.mock('expo-image-manipulator', () => ({
  manipulateAsync: jest.fn(),
  SaveFormat: { JPEG: 'jpeg', PNG: 'png' },
}));

jest.mock('../../../storage/local-attachments', () => ({
  readPickedLocalFile: jest.fn(),
  releaseTemporaryLocalFile: jest.fn(),
}));

const mockManipulateAsync = jest.requireMock('expo-image-manipulator').manipulateAsync as jest.Mock;
const localAttachments = jest.requireMock('../../../storage/local-attachments') as {
  readPickedLocalFile: jest.Mock;
  releaseTemporaryLocalFile: jest.Mock;
};
const original: ReceiptDocument = {
  byteSize: 10_000,
  createdAt: '2026-07-15T04:00:00.000Z',
  heightPixels: 2_400,
  id: '0ad845cb-2616-46e2-9ea7-baf9c480e283',
  isOriginal: true,
  mimeType: 'image/jpeg',
  originalFilename: 'synthetic-receipt.jpg',
  pageCount: 1,
  parentDocumentId: null,
  receiptId: 'b1c535d8-7295-46ac-aa11-c09ea335e8f4',
  sha256: 'd'.repeat(64),
  sourceType: 'image_import',
  storageDeletedAt: null,
  storageReference: 'receipt-documents/original.jpg',
  widthPixels: 1_800,
};

describe('Expo receipt preview creation', () => {
  beforeEach(() => {
    mockManipulateAsync.mockReset().mockResolvedValue({
      height: 1_600,
      uri: 'file:///cache/generated-preview.jpg',
      width: 1_200,
    });
    localAttachments.readPickedLocalFile.mockReset().mockResolvedValue(Uint8Array.from([1, 2, 3]));
    localAttachments.releaseTemporaryLocalFile.mockReset();
  });

  test('bounds the dominant dimension and persists generated bytes through the writer', async () => {
    const preview = { ...original, id: 'a187d7ba-99be-4b79-8f7f-a6cf86cd04cc' };
    const write = jest.fn().mockResolvedValue(preview);
    const creator = new ExpoReceiptPreviewCreator({ write });

    await expect(
      creator.create({
        createdAt: '2026-07-15T05:00:00.000Z',
        documentId: preview.id,
        original,
        sourceUri: 'file:///selected-receipt.jpg',
      }),
    ).resolves.toBe(preview);

    expect(mockManipulateAsync).toHaveBeenCalledWith(
      'file:///selected-receipt.jpg',
      [{ resize: { height: 1_600 } }],
      { compress: 0.82, format: 'jpeg' },
    );
    expect(write).toHaveBeenCalledWith({
      bytes: Uint8Array.from([1, 2, 3]),
      createdAt: '2026-07-15T05:00:00.000Z',
      documentId: preview.id,
      original,
    });
    expect(localAttachments.releaseTemporaryLocalFile).toHaveBeenCalledWith(
      'file:///cache/generated-preview.jpg',
    );
  });

  test('releases the temporary encoded file when persistence fails', async () => {
    const writer: Pick<AttachmentPreviewWriter, 'write'> = {
      write: jest.fn().mockRejectedValue(new Error('Synthetic persistence failure.')),
    };
    const creator = new ExpoReceiptPreviewCreator(writer);

    await expect(
      creator.create({
        createdAt: '2026-07-15T05:00:00.000Z',
        documentId: 'a187d7ba-99be-4b79-8f7f-a6cf86cd04cc',
        original,
        sourceUri: 'file:///selected-receipt.jpg',
      }),
    ).rejects.toThrow('Synthetic persistence failure.');
    expect(localAttachments.releaseTemporaryLocalFile).toHaveBeenCalledWith(
      'file:///cache/generated-preview.jpg',
    );
  });
});
