// SPDX-License-Identifier: GPL-3.0-only
import type { ReceiptDocumentRepository } from '@reimbursd/database';
import type { ReceiptDocument } from '@reimbursd/domain';
import { describe, expect, it, vi, type Mocked } from 'vitest';

import type { AttachmentHasher, AttachmentStorage } from './attachment-ingestor.js';
import {
  AttachmentPreviewValidationError,
  AttachmentPreviewWriter,
  type AttachmentPreviewLimits,
} from './attachment-preview.js';
import type { AttachmentInspection, AttachmentInspector } from './content-inspector.js';

const receiptId = 'b1c535d8-7295-46ac-aa11-c09ea335e8f4';
const originalId = '0ad845cb-2616-46e2-9ea7-baf9c480e283';
const previewId = 'a187d7ba-99be-4b79-8f7f-a6cf86cd04cc';
const sha256 = 'e'.repeat(64);
const createdAt = '2026-07-15T05:00:00.000Z';
const original: ReceiptDocument = {
  byteSize: 2_048,
  createdAt: '2026-07-15T04:00:00.000Z',
  heightPixels: 2_400,
  id: originalId,
  isOriginal: true,
  mimeType: 'image/jpeg',
  originalFilename: 'synthetic-receipt.jpg',
  pageCount: 1,
  parentDocumentId: null,
  receiptId,
  sha256: 'd'.repeat(64),
  sourceType: 'image_import',
  storageDeletedAt: null,
  storageReference: `receipt-documents/${receiptId}/originals/${originalId}.jpg`,
  widthPixels: 1_800,
};
const inspection: AttachmentInspection = {
  heightPixels: 1_200,
  mimeType: 'image/jpeg',
  pageCount: 1,
  widthPixels: 900,
};
const limits: AttachmentPreviewLimits = {
  maximumByteSize: 10,
  maximumDimension: 1_600,
  maximumPixels: 2_560_000,
};

describe('attachment preview persistence', () => {
  it('stores generated bytes as a separate derivative of the immutable original', async () => {
    const documents = createDocumentRepository();
    const storage = createStorage();
    const bytes = Uint8Array.from([1, 2, 3, 4]);
    const writer = createWriter({ documents, storage });

    const document = await writer.write({ bytes, createdAt, documentId: previewId, original });
    bytes.fill(9);

    expect(document).toEqual({
      byteSize: 4,
      createdAt,
      heightPixels: 1_200,
      id: previewId,
      isOriginal: false,
      mimeType: 'image/jpeg',
      originalFilename: 'receipt-preview.jpg',
      pageCount: 1,
      parentDocumentId: originalId,
      receiptId,
      sha256,
      sourceType: 'derivative',
      storageDeletedAt: null,
      storageReference: `receipt-documents/${receiptId}/derivatives/${previewId}.jpg`,
      widthPixels: 900,
    });
    expect(storage.writeOnce).toHaveBeenCalledWith(
      document.storageReference,
      Uint8Array.from([1, 2, 3, 4]),
    );
    expect(documents.create).toHaveBeenCalledWith(document);
  });

  it('rejects generated content that is not a bounded image', async () => {
    const storage = createStorage();
    const writer = createWriter({
      inspection: {
        heightPixels: null,
        mimeType: 'application/pdf',
        pageCount: 1,
        widthPixels: null,
      },
      storage,
    });

    await expect(
      writer.write({ bytes: Uint8Array.from([1]), createdAt, documentId: previewId, original }),
    ).rejects.toBeInstanceOf(AttachmentPreviewValidationError);
    expect(storage.writeOnce).not.toHaveBeenCalled();
  });

  it('rejects previews for deleted or non-image originals', async () => {
    const writer = createWriter();

    await expect(
      writer.write({
        bytes: Uint8Array.from([1]),
        createdAt,
        documentId: previewId,
        original: { ...original, storageDeletedAt: createdAt },
      }),
    ).rejects.toBeInstanceOf(AttachmentPreviewValidationError);
  });

  it('removes generated bytes when derivative metadata cannot be saved', async () => {
    const documents = createDocumentRepository();
    documents.create.mockRejectedValue(new Error('Synthetic database failure.'));
    const storage = createStorage();
    const writer = createWriter({ documents, storage });

    await expect(
      writer.write({ bytes: Uint8Array.from([1]), createdAt, documentId: previewId, original }),
    ).rejects.toThrow('Synthetic database failure.');
    expect(storage.delete).toHaveBeenCalledWith(
      `receipt-documents/${receiptId}/derivatives/${previewId}.jpg`,
    );
  });
});

function createWriter(
  overrides: {
    readonly documents?: Mocked<ReceiptDocumentRepository>;
    readonly inspection?: AttachmentInspection;
    readonly storage?: Mocked<AttachmentStorage>;
  } = {},
): AttachmentPreviewWriter {
  return new AttachmentPreviewWriter({
    documents: overrides.documents ?? createDocumentRepository(),
    hasher: { sha256: vi.fn<AttachmentHasher['sha256']>(async () => sha256) },
    inspector: {
      inspect: vi.fn<AttachmentInspector['inspect']>(
        async () => overrides.inspection ?? inspection,
      ),
    },
    limits,
    storage: overrides.storage ?? createStorage(),
  });
}

function createDocumentRepository(): Mocked<ReceiptDocumentRepository> {
  return {
    create: vi.fn<ReceiptDocumentRepository['create']>(async (document) => document),
    findOriginalByHash: vi.fn<ReceiptDocumentRepository['findOriginalByHash']>(),
    getById: vi.fn<ReceiptDocumentRepository['getById']>(),
    listByReceiptId: vi.fn<ReceiptDocumentRepository['listByReceiptId']>(),
    listPendingStorageDeletion: vi.fn<ReceiptDocumentRepository['listPendingStorageDeletion']>(),
    markStorageDeleted: vi.fn<ReceiptDocumentRepository['markStorageDeleted']>(),
  };
}

function createStorage(): Mocked<AttachmentStorage> {
  return {
    delete: vi.fn<AttachmentStorage['delete']>(),
    writeOnce: vi.fn<AttachmentStorage['writeOnce']>(),
  };
}
